name: jekyll
on:
  push: # for testing this action
  pull_request:
    paths:
      - '_data/**'
      - '.bundle/**'
      - 'assets/**'
      - 'index.*'
      - '_config.yml'
      - 'Gemfile*'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: 'jekyll build'
    steps:
    - name: checkout sc3-plugins
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: setup ruby and build
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler: 'Gemfile.lock'
        bundler-cache: true # this will run bundle install

