name: jekyll
on:
  push: # for testing this action
  pull_request:
    paths:
      - '_data/**'
      - '.bundle/**'
      - 'assets/**'
      - 'index.*'
      - '_config.yml'
      - 'Gemfile*'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: 'jekyll build'
    steps:
    - name: checkout sc3-plugins
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: install dependencies
      run: gem install bundler jekyll
    - name: build
      run: |
        # from https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem
        bundle config set force_ruby_platform true
        
        bundle install
